# Constants for daily-bible-calendar

# Google Calendar API scopes
SCOPES = ["https://www.googleapis.com/auth/calendar"]

# [openbible.com book number, stepbible.org book abbreviation, openbible.com book abbreviation]
BOOK_MAPPINGS = {
    "genesis": [1, "Gen", "Gen"],
    "exodus": [2, "Exod", "Exo"],
    "leviticus": [3, "Lev", "Lev"],
    "numbers": [4, "Num", "Num"],
    "deuteronomy": [5, "Deut", "Deu"],
    "joshua": [6, "Josh", "Jos"],
    "judges": [7, "Judg", "Jdg"],
    "ruth": [8, "Ruth", "Rut"],
    "1samuel": [9,"1Sam", "1Sa"],
    "2samuel": [10,"2Sam", "2Sa"],
    "1kings": [11,"1Kngs", "1Ki"],
    "2kings": [12,"2Kngs", "2Ki"],
    "1chronicles": [13,"1Chr", "1Ch"],
    "2chronicles": [14,"2Chr", "2Ch"],
    "ezra": [15,"Ezra", "Ezr"],
    "nehemiah": [16,"Neh", "Neh"],
    "esther": [17,"Esth", "Est"],
    "job": [18,"Job", "Job"],
    "psalms": [19,"Psalm", "Psa"],
    "proverbs": [20,"Prov", "Pro"],
    "ecclesiastes": [21,"Eccl", "Ecc"],
    "songofsongs": [22,"Song", "Sng"],
    "isaiah": [23,"Isa", "Isa"],
    "jeremiah": [24,"Jer", "Jer"],
    "lamentations": [25,"Lam", "Lam"],
    "ezekiel": [26,"Ezek", "Ezk"],
    "daniel": [27,"Dan", "Dan"],
    "hosea": [28,"Hosea", "Hos"],
    "joel": [29,"Joel", "Jol"],
    "amos": [30,"Amos", "Amo"],
    "obadiah": [31,"Obad", "Oba"],
    "jonah": [32,"Jonah", "Jon"],
    "micah": [33,"Micah", "Mic"],
    "nahum": [34,"Nahum", "Nam"],
    "habakkuk": [35,"Hab", "Hab"],
    "zephaniah": [36,"Zeph", "Zep"],
    "haggai": [37,"Hag", "Hag"],
    "zechariah": [38,"Zech", "Zec"],
    "malachi": [39,"Mal", "Mal"],
    "matthew": [40,"Matt", "Mat"],
    "mark": [41,"Mark", "Mrk"],
    "luke": [42,"Luke", "Luk"],
    "john": [43,"John", "Jhn"],
    "acts": [44,"Acts", "Act"],
    "romans": [45,"Rom", "Rom"],
    "1corinthians": [46,"1Cor", "1Co"],
    "2corinthians": [47,"2Cor", "2Co"],
    "galatians": [48,"Gal", "Gal"],
    "ephesians": [49,"Eph", "Eph"],
    "philippians": [50,"Phil", "Php"],
    "colossians": [51,"Col", "Col"],
    "1thessalonians": [52,"1Thess", "1Th"],
    "2thessalonians": [53,"2Thess", "2Th"],
    "1timothy": [54,"1Tim", "1Ti"],
    "2timothy": [55,"2Tim", "2Ti"],
    "titus": [56,"Titus", "Tts"],
    "philemon": [57,"Phlm", "Phm"],
    "hebrews": [58,"Heb", "Heb"],
    "james": [59,"James", "Jas"],
    "1peter": [60,"1Pet", "1Pe"],
    "2peter": [61,"2Pet", "2Pe"],
    "1john": [62,"1John", "1Jn"],
    "2john": [63,"2John", "2Jn"],
    "3john": [64,"3John", "3Jn"],
    "jude": [65,"Jude", "Jud"],
    "revelation": [66,"Rev", "Rev"],
}
